# Introduction to NumPy

### Import

In [1]:
import numpy as np

### Array Creation

In [2]:
# Create a 1-dimensional array
a = np.array([1,4,2,3,5,7,8,6])
print(a)

[1 4 2 3 5 7 8 6]


In [3]:
# Create a 2-dimensional array
b = np.array([[5,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(b)

[[5 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]


In [4]:
# Create a 2x2 array of all zeros
print('A 2x2 array of all zeros')
print(np.zeros((2, 2)))
print()

A 2x2 array of all zeros
[[0. 0.]
 [0. 0.]]



In [5]:
# Create an 1x2 array of all ones
print('An 1x2 array of all ones')
print(np.ones((1, 2)))
print()

An 1x2 array of all ones
[[1. 1.]]



In [6]:
# Create a 2x2 constant array of the number 7
print('A 2x2 constant array of the number 7')
print(np.full((2, 2), 7))
print()

A 2x2 constant array of the number 7
[[7 7]
 [7 7]]



In [10]:
# Creates a 2x2 array filled with random values between 0 and 1
print('A 2x2 array filled with random values between 0 and 1')
np.random.seed(42) # set a seed to that we always get the same random values
c = np.random.random((2, 2))
print(c)

A 2x2 array filled with random values between 0 and 1
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [11]:
# Create a 2x2 identity matrix
print('A 2x2 identity matrix')
print(np.eye(2))

A 2x2 identity matrix
[[1. 0.]
 [0. 1.]]


### Reading documentation

In [12]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

### Defining features of NumPy Arrays

#### Shape and Size

In [13]:
print('Shape of NumPy array "a"')
print(a.shape)
print()
 
print('Shape of NumPy array "b"')
print(b.shape)

Shape of NumPy array "a"
(8,)

Shape of NumPy array "b"
(3, 6)


In [14]:
print('Number of dimensions of NumPy array "a"')
print(a.ndim)
print()
 
print('Number of dimensions of NumPy array "b"')
print(b.ndim)

Number of dimensions of NumPy array "a"
1

Number of dimensions of NumPy array "b"
2


In [15]:
print('Total number of elements in NumPy array "a"')
print(a.size)
print()
 
print('Total number of elements in NumPy array "b"')
print(b.size)
print()
 
print('Total number of elements in NumPy array "c"')
print(c.size)

Total number of elements in NumPy array "a"
8

Total number of elements in NumPy array "b"
18

Total number of elements in NumPy array "c"
4


#### Datatype

In [16]:
print('Type of data stored in NumPy array "a"')
print(a.dtype.name)
print()
 
print('Type of data stored in NumPy array "b"')
print(b.dtype.name)
print()
 
print('Type of data stored in NumPy array "c"')
print(c.dtype.name)

Type of data stored in NumPy array "a"
int64

Type of data stored in NumPy array "b"
int64

Type of data stored in NumPy array "c"
float64


In [17]:
print('Size of an individual array elements in NumPy array "a"')
print(a.itemsize)
print()
 
print('Size of an individual array elements in NumPy array "b"')
print(b.itemsize)
print()
 
print('Size of an individual array elements in NumPy array "c"')
print(c.itemsize)

Size of an individual array elements in NumPy array "a"
8

Size of an individual array elements in NumPy array "b"
8

Size of an individual array elements in NumPy array "c"
8


In [18]:
print(type(a))

<class 'numpy.ndarray'>


In [19]:
# Create an array of zeroes of the same shape as "b"
print('A new array of zeroes of the same shape as "b"')
print(np.zeros(b.shape))
print()
# Create an array of ones of the same shape as "a"
print('A new array of ones of the same shape as "a"')
print(np.ones(a.shape))

A new array of zeroes of the same shape as "b"
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

A new array of ones of the same shape as "a"
[1. 1. 1. 1. 1. 1. 1. 1.]


### Slicing and Indexing

#### Indexing

In [20]:
# Recall what array a looked like
print('array "a"')
print(a)
print()
 
# Indexing. As always, indexes start from 0.
print('First element of array "a"')
print(a[0])   # element 1 
print()
print('Second element of array "a"')
print(a[1])   # element 2 

array "a"
[1 4 2 3 5 7 8 6]

First element of array "a"
1

Second element of array "a"
4


In [21]:
# Recall what array b looked like
print('array "b"')
print(b)
print()
 
# Indexing. As always, indexes start from 0.
print('Element from row 0, column 1, of array "b"')
print(b[0, 1])   # (row 0, column 1)

array "b"
[[5 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

Element from row 0, column 1, of array "b"
0


#### Slicing

In [22]:
# Slicing pulls out a subarray 
# Example for pulling out elements 2 through 4
# (element 2 is included and 4 is not, same as python list slicing).
print('Elements 2 through 4 (4 not included), of array "a"') 
print(a[2:4])   
print()
# Example for pulling out first 3 elements
print('First 3 elements of array "a"')
print(a[:3])

Elements 2 through 4 (4 not included), of array "a"
[2 3]

First 3 elements of array "a"
[1 4 2]


In [23]:
# Example for pulling out first 2 rows and columns 1 though 3 
# (column 1 is included and 3 is not, same as python list slicing). 
print('First 2 rows and columns 1 through 3 (3 not included) of array "b" ')
print(b[:2, 1:3])
print()
 
# Values from row 1 through 2 and all columns
print('Values from row 1 through 2 and all columns, of array "b"')
print(b[1:2, :])
print()
 
# Values from all rows and column 2
print('Values from all rows and column 2')
print(b[:, 2])

First 2 rows and columns 1 through 3 (3 not included) of array "b" 
[[0 1]
 [3 0]]

Values from row 1 through 2 and all columns, of array "b"
[[1 3 0 1 2 0]]

Values from all rows and column 2
[1 0 0]


#### Modifying Elements

In [24]:
b[0, 0] = 7  # sets the first value in the first column to 7. 
print(b) 

[[7 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]


In [25]:
d = np.copy(b)
d[1:3, 2:4] = 9  # sets all values in the subarray to 9. 
print(d)

[[7 0 1 0 2 3]
 [1 3 9 9 2 0]
 [0 1 9 9 1 3]]


In [26]:
d[:2, 1:3] = np.array([[2, 0], [4, 3]])
print(d)

[[7 2 0 0 2 3]
 [1 4 3 9 2 0]
 [0 1 9 9 1 3]]


#### Conditionals and Conditional Indexing

In [27]:
# Recall what array a looked like
print('array "a"')
print(a)
print()
print('Conditional of array "a", for elements of "a" greater than 2')
print(a > 2)

array "a"
[1 4 2 3 5 7 8 6]

Conditional of array "a", for elements of "a" greater than 2
[False  True False  True  True  True  True  True]


In [28]:
print('Values of array "a" larger than 2')
print(a[a > 2]) # values of a larger than 2

Values of array "a" larger than 2
[4 3 5 7 8 6]


In [29]:
# Recall what array b looked like
print('array "b"')
print(b)
print()
 
print('Conditional of array "b", for elements of "b" greater than 2')
print(b > 2)
print()
print('Values of array "b" larger than 2') 
print(b[b > 2])


array "b"
[[7 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

Conditional of array "b", for elements of "b" greater than 2
[[ True False False False False  True]
 [False  True False False False False]
 [False False False False False  True]]

Values of array "b" larger than 2
[7 3 3 3]
