### Set Up

In [1]:
import numpy as np
 
# Create a 1-dimensional array
a = np.array([1,4,2,3,5,7,8,6])
print('array "a"')
print(a)
print()
 
# Create a 2-dimensional array
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print('array "b"')
print(b)

array "a"
[1 4 2 3 5 7 8 6]

array "b"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]


### Element-wise operations (add, multiply, etc)

In [6]:
c = b + 5 
print(c)

[[6 5 6 5 7 8]
 [6 8 5 6 7 5]
 [5 6 5 5 6 8]]


In [7]:
# Element-wise addition
print('Element-wise sum of "b" and "c"') 
print(b + c)
print()
 
print('Element-wise sum of "b" and "c"') 
print(np.add(b, c))

Element-wise sum of "b" and "c"
[[ 7  5  7  5  9 11]
 [ 7 11  5  7  9  5]
 [ 5  7  5  5  7 11]]

Element-wise sum of "b" and "c"
[[ 7  5  7  5  9 11]
 [ 7 11  5  7  9  5]
 [ 5  7  5  5  7 11]]


In [8]:
# Element-wise subtraction 
print('Element-wise difference of "b" and "c"') 
print(b - c)
print()
print('Element-wise difference of "b" and "c"')  
print(np.subtract(b, c))

Element-wise difference of "b" and "c"
[[-5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5]]

Element-wise difference of "b" and "c"
[[-5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5]]


In [9]:
# Element-wise multiplication 
print('Element-wise multiplication of "b" and "c"')
print(b * c)
print()
print('Element-wise multiplication of "b" and "c"') 
print(np.multiply(b, c))

Element-wise multiplication of "b" and "c"
[[ 6  0  6  0 14 24]
 [ 6 24  0  6 14  0]
 [ 0  6  0  0  6 24]]

Element-wise multiplication of "b" and "c"
[[ 6  0  6  0 14 24]
 [ 6 24  0  6 14  0]
 [ 0  6  0  0  6 24]]


In [10]:
# Element-wise division
print('Element-wise division of "b" and "c" ')
print(b / c)

Element-wise division of "b" and "c" 
[[0.16666667 0.         0.16666667 0.         0.28571429 0.375     ]
 [0.16666667 0.375      0.         0.16666667 0.28571429 0.        ]
 [0.         0.16666667 0.         0.         0.16666667 0.375     ]]


In [11]:
# Element-wise square-root
print('Element-wise square root of array "b"')
print(np.sqrt(b))

Element-wise square root of array "b"
[[1.         0.         1.         0.         1.41421356 1.73205081]
 [1.         1.73205081 0.         1.         1.41421356 0.        ]
 [0.         1.         0.         0.         1.         1.73205081]]


In [13]:
# Element-wise square-root
print('Element-wise square root of array "b"')
print(np.log(c))

Element-wise square root of array "b"
[[1.79175947 1.60943791 1.79175947 1.60943791 1.94591015 2.07944154]
 [1.79175947 2.07944154 1.60943791 1.79175947 1.94591015 1.60943791]
 [1.60943791 1.79175947 1.60943791 1.60943791 1.79175947 2.07944154]]


In [14]:
# Element-wise square-root
print('Element-wise square root of array "b"')
print(np.exp(c))

Element-wise square root of array "b"
[[ 403.42879349  148.4131591   403.42879349  148.4131591  1096.63315843
  2980.95798704]
 [ 403.42879349 2980.95798704  148.4131591   403.42879349 1096.63315843
   148.4131591 ]
 [ 148.4131591   403.42879349  148.4131591   148.4131591   403.42879349
  2980.95798704]]


### Aggregation operations (sum, min, max, etc)

In [15]:
# Sum of all elements
print('Sum of all elements of array "b"')
print(b.sum())
print()
 
# Sum of each column
print('Sum of each column of array "b"')
print(b.sum(axis=0))
print()
 
# Sum of each row
print('Sum of each row of array "b"')
print(b.sum(axis=1))

Sum of all elements of array "b"
19

Sum of each column of array "b"
[2 4 1 1 5 6]

Sum of each row of array "b"
[7 7 5]


In [16]:
# Minimum of all values
print('Minimum of all values of array "b"') 
print(b.min())
print()
 
# Maximum across axis 1
print('Maximum across axis 1 of array "b"')
print(b.max(axis=1))
print()
 
# Cumulative sum across axis 0
print('Cumulative sum across axis 0 of array "b"')
print(b.cumsum(axis=0))

Minimum of all values of array "b"
0

Maximum across axis 1 of array "b"
[3 3 3]

Cumulative sum across axis 0 of array "b"
[[1 0 1 0 2 3]
 [2 3 1 1 4 3]
 [2 4 1 1 5 6]]


In [18]:
print('Mean along axis 0 of array "b"')
print(b.mean(axis=0))
print()
 
print('Median along axis 1 of array "b"')
print(np.median(b, axis=1))
print()
 
print('Standard deviation along axis 0 of array "b"')
print(np.std(b, axis=0))
print()
 
print('Mean along axis 0 of array "b"')
print(np.mean(b, axis=0))

Mean along axis 0 of array "b"
[0.66666667 1.33333333 0.33333333 0.33333333 1.66666667 2.        ]

Median along axis 1 of array "b"
[1.  1.  0.5]

Standard deviation along axis 0 of array "b"
[0.47140452 1.24721913 0.47140452 0.47140452 0.47140452 1.41421356]

Mean along axis 0 of array "b"
[0.66666667 1.33333333 0.33333333 0.33333333 1.66666667 2.        ]


In [19]:
print('unique elements in array "b"')
print(np.unique(b))

unique elements in array "b"
[0 1 2 3]


### Matrix Operations (dot products, matrix multiplication, etc)

In [20]:
# Create array "v"
v = b[:, 0]
print('array "v"')
print(v)
print()
# Create array "w"
w = b[:, 1]
print('array "w"')
print(w)

array "v"
[1 1 0]

array "w"
[0 3 1]


In [21]:
# Inner product of vectors: v[0]*w[0] + v[1]*w[1] + ... v[n]*w[n]
print('Dot product of "v" and "w"')
print(v.dot(w)) # or np.dot(v, w)
print()
 
print('Dot product of "v" and "v"')
print(v.dot(v)) # or np.dot(v, v)

Dot product of "v" and "w"
3

Dot product of "v" and "v"
2


In [22]:
# Transpose of a matrix
print('Transpose of "b"')
print(b.T)
print()
 
# Matrix-vector product
print('Matrix-vector product of "b-transpose" and "v"')
print(np.dot(b.T, v))
print()
 
# Matrix-matrix product (matrix multiplication)
print('Matrix-matrix product of "b-transpose" and "b"')
print(np.dot(b.T, b))

Transpose of "b"
[[1 1 0]
 [0 3 1]
 [1 0 0]
 [0 1 0]
 [2 2 1]
 [3 0 3]]

Matrix-vector product of "b-transpose" and "v"
[2 3 1 1 4 3]

Matrix-matrix product of "b-transpose" and "b"
[[ 2  3  1  1  4  3]
 [ 3 10  0  3  7  3]
 [ 1  0  1  0  2  3]
 [ 1  3  0  1  2  0]
 [ 4  7  2  2  9  9]
 [ 3  3  3  0  9 18]]


In [23]:
# Incompatible dimensions (matrix-vector)
print(np.dot(b, v))

ValueError: shapes (3,6) and (3,) not aligned: 6 (dim 1) != 3 (dim 0)

In [24]:
# Incompatible dimensions (matrix-matrix)
print(np.dot(b, c))

ValueError: shapes (3,6) and (3,6) not aligned: 6 (dim 1) != 3 (dim 0)

### Sorting

In [25]:
print('array "a"')
print(a)
print()
 
# sort array "a"
print('sorted array "a"')
print(np.sort(a))

array "a"
[1 4 2 3 5 7 8 6]

sorted array "a"
[1 2 3 4 5 6 7 8]


In [26]:
print('array "b"')
print(b)
print()
# sort array "b" along rows, axis 1
print('array "b" sorted along rows (axis=1)')
print(np.sort(b, axis=1))
print()
# sort array "b" along rows (also the last axis in this case)
print('array "b" sorted along rows (axis=-1)')
print(np.sort(b, axis=-1))
print()
# sort array "b" along columns, axis 0
print('array "b" sorted along columns (axis=0)')
print(np.sort(b, axis=0))
print()
# sort array "b" after flattening it
print('array "b" flattened and then sorted (axis=None)')
print(np.sort(b, axis=None))

array "b"
[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]

array "b" sorted along rows (axis=1)
[[0 0 1 1 2 3]
 [0 0 1 1 2 3]
 [0 0 0 1 1 3]]

array "b" sorted along rows (axis=-1)
[[0 0 1 1 2 3]
 [0 0 1 1 2 3]
 [0 0 0 1 1 3]]

array "b" sorted along columns (axis=0)
[[0 0 0 0 1 0]
 [1 1 0 0 2 3]
 [1 3 1 1 2 3]]

array "b" flattened and then sorted (axis=None)
[0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 3 3 3]


In [27]:
# create a new array with 'nan' values 
z = np.array([0, np.nan, 1, 2, np.nan, 7, 3, 5, 1, np.nan])
print('array with "nan" values')
print(z)
print()
 
# sort array and display
print('sorted array')
print(np.sort(z))

array with "nan" values
[ 0. nan  1.  2. nan  7.  3.  5.  1. nan]

sorted array
[ 0.  1.  1.  2.  3.  5.  7. nan nan nan]


In [28]:
b.sort(axis=0)
print(b)

[[0 0 0 0 1 0]
 [1 1 0 0 2 3]
 [1 3 1 1 2 3]]
